a= int (input ("Enter the number : "))

print ("Square of the given num is ",a**2)
# a** anything will like power easily can be done a sq, cube , .... 
# alternatively you can do like a*a for sqaure or a*a*a for a cube ... 
# also sqare root or cube root we can calculate a**(1/2) like in this way ...